apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: icpk9cazn-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/icpk9cazn-java-quarkus-gitops